services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: django_backend
    restart: on-failure
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=user
      - DB_PASSWORD=password
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: vue_frontend
    restart: no
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  mysql_data:
