services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    image: python:3.13
    container_name: django_backend
    restart: no
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install -r requirements.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db

  frontend:
    image: node:lts
    container_name: vue_frontend
    restart: no
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install &&
             npm run build &&
             npx http-server dist -p 5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend


volumes:
  mysql_data: